### ISSUE TITLE
Disconnect every 20 seconds

### ISSUE THREAD

**Issue by jflefebvre06** [AlexxIT/Jura#7]
Hello,
Thanks a lot for the job, perfectly works with my Jura **S80**, the only problem I have is it disconnect every 20 seconds

![image](https://github.com/AlexxIT/Jura/assets/2685607/62dba965-aadf-4b64-b714-d93423d23374)

I use atom bluetooth proxy

```yaml
substitutions:
  name: atom-bluetooth-proxy
  board: m5stack-atom
  mac: 0d350c

esphome:
  name: ${name}
  name_add_mac_suffix: true

esp32:
  board: ${board}
  framework:
    type: esp-idf

# Enable Home Assistant API
api:

# Enable logging
logger:

ota:

improv_serial:

# captive_portal:

bluetooth_proxy:
  active: true

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: ${name}-${mac}.local

esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true
```

Do you have implemented the [heartbeat](https://github.com/Jutta-Proto/protocol-bt-cpp/tree/main#heartbeat) ?
